"""Export split optimal-LR and last-iterate-risk heatmaps from CSV.

This reads the grid CSV produced by run_last_iter_risk_heatmap.py and writes
two standalone heatmap figures (optimal LR and last-iterate risk), typically as
PDF for manuscript inclusion.
"""

from __future__ import annotations

import argparse
import csv
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np


def _overlay_phase_boundaries(ax: plt.Axes, *, sigma: float, kappa_min: float, kappa_max: float) -> None:
    k1 = sigma - 1.0
    k2 = sigma
    if kappa_min <= k1 <= kappa_max:
        ax.axvline(k1, color="white", lw=1.2, ls=":")
    if kappa_min <= k2 <= kappa_max:
        ax.axvline(k2, color="white", lw=1.2, ls=":")
    xs = np.linspace(kappa_min, kappa_max, 300)
    ys = 1.0 - sigma + xs
    ax.plot(xs, ys, color="white", lw=1.2, ls="-")


def _to_log10(arr: np.ndarray) -> np.ndarray:
    out = np.full_like(arr, np.nan, dtype=float)
    mask = np.isfinite(arr) & (arr > 0.0)
    out[mask] = np.log10(arr[mask])
    return out


def _plot_single(
    *,
    data: np.ndarray,
    kappa_min: float,
    kappa_max: float,
    gamma_min: float,
    gamma_max: float,
    sigma: float,
    title: str,
    cbar_label: str,
    cmap_name: str,
    out_path: Path,
) -> None:
    out_path.parent.mkdir(parents=True, exist_ok=True)
    fig, ax = plt.subplots(1, 1, figsize=(6.0, 4.8))
    cmap = plt.get_cmap(cmap_name).copy()
    cmap.set_bad(color="lightgray")
    im = ax.imshow(
        data,
        origin="lower",
        extent=[kappa_min, kappa_max, gamma_min, gamma_max],
        aspect="auto",
        cmap=cmap,
    )
    _overlay_phase_boundaries(ax, sigma=sigma, kappa_min=kappa_min, kappa_max=kappa_max)
    ax.set_xlabel(r"$\kappa$")
    ax.set_ylabel(r"$\gamma$")
    ax.set_title(title)
    cbar = fig.colorbar(im, ax=ax)
    cbar.set_label(cbar_label)
    fig.tight_layout()
    fig.savefig(out_path)
    plt.close(fig)


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument(
        "--in-csv",
        type=Path,
        default=Path("simulations/outputs/master_ode_last_iter_grid_highres.csv"),
        help="Input CSV generated by run_last_iter_risk_heatmap.py.",
    )
    p.add_argument("--sigma", type=float, default=1.2, help="Batch exponent for boundary overlays.")
    p.add_argument(
        "--out-opt-pdf",
        type=Path,
        default=Path("simulations/outputs/master_ode_last_iter_opt_lr_highres.pdf"),
    )
    p.add_argument(
        "--out-risk-pdf",
        type=Path,
        default=Path("simulations/outputs/master_ode_last_iter_risk_highres.pdf"),
    )
    return p.parse_args()


def main() -> None:
    args = parse_args()

    rows: list[dict[str, str]] = []
    with args.in_csv.open(newline="", encoding="utf-8") as f:
        rows = list(csv.DictReader(f))
    if not rows:
        raise RuntimeError(f"Empty CSV: {args.in_csv}")

    kappas = sorted({float(r["kappa"]) for r in rows})
    gammas = sorted({float(r["gamma"]) for r in rows})
    nk = len(kappas)
    ng = len(gammas)
    if nk < 2 or ng < 2:
        raise RuntimeError("CSV must contain at least a 2x2 grid.")

    k_to_i = {k: i for i, k in enumerate(kappas)}
    g_to_i = {g: i for i, g in enumerate(gammas)}

    eta_opt_grid = np.full((ng, nk), np.nan, dtype=float)
    risk_opt_grid = np.full((ng, nk), np.nan, dtype=float)

    for r in rows:
        k = float(r["kappa"])
        g = float(r["gamma"])
        i = k_to_i[k]
        j = g_to_i[g]
        eta_opt_grid[j, i] = float(r["eta_opt"])
        risk_opt_grid[j, i] = float(r["risk_opt"])

    kappa_min = float(kappas[0])
    kappa_max = float(kappas[-1])
    gamma_min = float(gammas[0])
    gamma_max = float(gammas[-1])

    _plot_single(
        data=_to_log10(eta_opt_grid),
        kappa_min=kappa_min,
        kappa_max=kappa_max,
        gamma_min=gamma_min,
        gamma_max=gamma_max,
        sigma=float(args.sigma),
        title=r"Optimal LR: $\log_{10}\eta_\star$",
        cbar_label=r"$\log_{10}\eta_\star$",
        cmap_name="viridis",
        out_path=args.out_opt_pdf,
    )
    _plot_single(
        data=_to_log10(risk_opt_grid),
        kappa_min=kappa_min,
        kappa_max=kappa_max,
        gamma_min=gamma_min,
        gamma_max=gamma_max,
        sigma=float(args.sigma),
        title=r"Last-Iterate Risk: $\log_{10}R_{\mathrm{last}}$",
        cbar_label=r"$\log_{10}R_{\mathrm{last}}$",
        cmap_name="viridis",
        out_path=args.out_risk_pdf,
    )


if __name__ == "__main__":
    main()

